"""Generate the GitHub Pages site: python3 tools/build_site.py."""
from pathlib import Path
import html, json
ROOT = Path(__file__).resolve().parents[1]
BASE = 'https://www.anotherdoor.io'
LOCALES = {
'en': ['English','Small steps.','Better days.','Thoughtful apps for your mornings, habits, and everyday spending.','Explore our apps','Our apps','About us','Contact','Made for your everyday.','Three small tools. A little more room to live.','Wake up. Show up. Keep track.','We make lifestyle apps that help you shape a better day. From getting out of bed to building habits and recording everyday spending, Another Door creates thoughtful tools for the moments that matter.','Easy to start','Simple tools that fit into your everyday life.','Keep going','Build a rhythm, one small step at a time.','See your progress','Make everyday changes easier to notice.','Let’s open another door.','Questions, feedback, or a hello — we’d love to hear from you.','Discover the app','All apps','Privacy policy','Screens from the app','Mornings','Habits','Spending','Start your day proud.','Small habits. Visible growth.','Your spending, at a glance.','Wake up with a mission, find a little inspiration, and make your morning yours.','Build your routines, keep your streak, and watch small steps add up.','Record everyday expenses and see your recent spending in one clear view.',['Mission alarms','Daily inspiration','Focus timer'],['Habits & routines','Growth terrarium','Progress insights'],['Expense recording','Recent expenses','Monthly overview']],
'ko': ['한국어','작은 변화로,','더 나은 하루.','아침을 깨우고, 습관을 이어가고, 일상의 지출을 기록하는 앱을 만듭니다.','앱 살펴보기','우리의 앱','회사 소개','문의','매일의 순간을 위해.','세 가지 작은 도구로 일상에 여유를 더하세요.','일어나고. 이어가고. 기록하고.','Another Door는 더 나은 하루를 만드는 라이프스타일 앱을 만듭니다. 아침에 일어나고, 습관을 이어가고, 일상의 지출을 기록하는 순간마다 쉽게 시작하고 꾸준히 사용할 수 있는 도구를 제공합니다.','쉽게 시작하기','일상에 자연스럽게 어울리는 간단한 도구.','꾸준히 이어가기','작은 실천으로 나만의 리듬을 만드세요.','변화를 확인하기','매일의 작은 변화를 한눈에 확인하세요.','새로운 일상의 문을 열어요.','질문이나 의견이 있으신가요? 편하게 연락해 주세요.','앱 자세히 보기','모든 앱','개인정보처리방침','앱 화면','아침','습관','지출','뿌듯한 하루의 시작.','작은 습관이 자라는 순간.','오늘의 지출을 한눈에.','미션으로 잠을 깨우고, 영감을 얻고, 나만의 아침을 만들어 보세요.','루틴을 만들고 꾸준히 실천하며 작은 변화가 쌓이는 모습을 확인하세요.','일상의 지출을 기록하고 최근 소비 내역을 한눈에 확인하세요.',['미션 알람','매일의 영감','집중 타이머'],['습관과 루틴','성장 테라리움','진행 상황 통계'],['지출 기록','최근 소비 내역','월별 지출 요약']],
'de': ['Deutsch','Kleine Schritte.','Bessere Tage.','Durchdachte Apps für deinen Morgen, deine Gewohnheiten und deine täglichen Ausgaben.','Apps entdecken','Unsere Apps','Über uns','Kontakt','Für deinen Alltag gemacht.','Drei kleine Helfer. Mehr Raum fürs Leben.','Aufwachen. Dranbleiben. Überblick behalten.','Another Door entwickelt Lifestyle-Apps für einen besseren Alltag. Vom Aufstehen über neue Gewohnheiten bis zum Erfassen deiner Ausgaben: Wir gestalten einfache Werkzeuge für die Momente, die zählen.','Einfach anfangen','Einfache Werkzeuge, die in deinen Alltag passen.','Dranbleiben','Finde deinen Rhythmus, Schritt für Schritt.','Fortschritte sehen','Erkenne die kleinen Veränderungen im Alltag.','Öffnen wir eine neue Tür.','Fragen, Feedback oder ein Hallo — wir freuen uns auf dich.','App kennenlernen','Alle Apps','Datenschutz','Einblicke in die App','Morgen','Gewohnheiten','Ausgaben','Starte stolz in den Tag.','Kleine Gewohnheiten. Sichtbares Wachstum.','Deine Ausgaben auf einen Blick.','Wache mit einer Mission auf, finde Inspiration und gestalte deinen Morgen.','Gestalte Routinen, bleib dran und sieh, wie kleine Schritte sich summieren.','Erfasse tägliche Ausgaben und behalte deine letzten Ausgaben im Blick.',['Missionsalarme','Tägliche Inspiration','Fokustimer'],['Gewohnheiten & Routinen','Wachstumsterrarium','Fortschrittsübersicht'],['Ausgaben erfassen','Letzte Ausgaben','Monatsübersicht']],
'es': ['Español','Pequeños pasos.','Mejores días.','Apps pensadas para tus mañanas, tus hábitos y tus gastos diarios.','Explora nuestras apps','Nuestras apps','Sobre nosotros','Contacto','Para tu día a día.','Tres pequeñas herramientas. Más espacio para vivir.','Despierta. Sigue adelante. Lleva el control.','Another Door crea apps para mejorar tu día a día. Desde levantarte hasta crear hábitos y registrar tus gastos, diseñamos herramientas sencillas para los momentos que importan.','Empieza fácilmente','Herramientas sencillas que encajan en tu vida.','Sigue adelante','Encuentra tu ritmo, paso a paso.','Ve tu progreso','Descubre los pequeños cambios de cada día.','Abramos otra puerta.','Preguntas, comentarios o un saludo: nos encantará escucharte.','Descubre la app','Todas las apps','Privacidad','Pantallas de la app','Mañanas','Hábitos','Gastos','Empieza el día con orgullo.','Pequeños hábitos. Crecimiento visible.','Tus gastos de un vistazo.','Despierta con una misión, encuentra inspiración y haz tuya la mañana.','Crea rutinas, mantén tu racha y observa cómo se suman los pequeños pasos.','Registra tus gastos diarios y consulta tus movimientos recientes con claridad.',['Alarmas con misiones','Inspiración diaria','Temporizador de enfoque'],['Hábitos y rutinas','Terrario de crecimiento','Estadísticas de progreso'],['Registro de gastos','Gastos recientes','Resumen mensual']],
'ja': ['日本語','小さな一歩で、','より良い毎日へ。','朝の目覚め、習慣づくり、日々の支出記録をサポートするアプリ。','アプリを見る','アプリ','会社について','お問い合わせ','毎日のためのアプリ。','3つの小さなツールで、暮らしにゆとりを。','目覚める。続ける。記録する。','Another Doorは、より良い毎日をつくるライフスタイルアプリを開発しています。朝の目覚めから習慣づくり、日々の支出記録まで、大切な瞬間に寄り添う使いやすいツールを届けます。','気軽に始める','日常になじむシンプルなツール。','一歩ずつ続ける','小さな一歩で、自分のリズムを。','変化を感じる','毎日の小さな変化を見える形に。','新しい扉を開こう。','ご質問、ご意見、お気軽にご連絡ください。','詳しく見る','すべてのアプリ','プライバシー','アプリの画面','朝','習慣','支出','誇れる一日の始まり。','小さな習慣が、目に見える成長に。','支出をひと目で。','ミッションで目覚め、ひらめきを見つけ、自分らしい朝を。','ルーティンを作り、継続し、小さな一歩の積み重ねを実感。','日々の支出を記録し、最近の出費をわかりやすく確認。',['ミッションアラーム','毎日のインスピレーション','集中タイマー'],['習慣とルーティン','成長テラリウム','進捗の統計'],['支出の記録','最近の支出','月別の概要']],
'zh-cn': ['简体中文','小小改变，','更好的每一天。','用心打造的应用，陪伴你的清晨、习惯养成和日常消费记录。','探索应用','我们的应用','关于我们','联系我们','为日常而设计。','三个小工具，让生活多一点从容。','醒来。坚持。记录。','Another Door 致力于打造改善日常生活的应用。从早晨起床到养成习惯，再到记录日常支出，我们为每个重要时刻提供简单、贴心的工具。','轻松开始','自然融入日常生活的简单工具。','持续前进','一步一步，找到自己的节奏。','看见进步','让每天的小改变清晰可见。','打开另一扇门。','有问题、建议或想打个招呼？欢迎联系我们。','了解应用','所有应用','隐私政策','应用界面','清晨','习惯','支出','自豪地开启新一天。','小习惯，看得见的成长。','支出一目了然。','通过任务唤醒自己，收获灵感，打造属于你的清晨。','建立日常习惯，坚持打卡，见证小小努力不断积累。','记录日常支出，清晰查看最近的消费。',['任务闹钟','每日灵感','专注计时器'],['习惯与日常计划','成长生态瓶','进度统计'],['支出记录','最近支出','月度概览']],
'fr': ['Français','Petits pas.','De meilleurs jours.','Des apps pensées pour vos matins, vos habitudes et vos dépenses quotidiennes.','Découvrir nos apps','Nos apps','À propos','Contact','Pour votre quotidien.','Trois petits outils. Plus de place pour vivre.','Se réveiller. Persévérer. Garder le fil.','Another Door crée des apps pour améliorer le quotidien. Du réveil aux habitudes en passant par le suivi des dépenses, nous concevons des outils simples pour les moments qui comptent.','Commencer simplement','Des outils simples qui trouvent leur place dans votre vie.','Continuer','Trouvez votre rythme, un petit pas à la fois.','Voir ses progrès','Rendez visibles les petits changements du quotidien.','Ouvrons une nouvelle porte.','Une question, un avis ou un bonjour ? Écrivez-nous.','Découvrir l’app','Toutes les apps','Confidentialité','Aperçu de l’app','Matins','Habitudes','Dépenses','Commencez la journée avec fierté.','Petites habitudes. Progrès visibles.','Vos dépenses en un coup d’œil.','Réveillez-vous avec une mission, trouvez de l’inspiration et créez votre matin.','Créez vos routines, gardez le rythme et voyez vos petits pas s’accumuler.','Notez vos dépenses quotidiennes et consultez clairement vos dernières dépenses.',['Alarmes à missions','Inspiration quotidienne','Minuteur de concentration'],['Habitudes et routines','Terrarium de croissance','Statistiques de progression'],['Saisie des dépenses','Dépenses récentes','Aperçu mensuel']]
}
PRODUCTS = [('waky-alarm','waky_alarm','Waky Alarm','6748906275','io.anotherdoor.wakyAlarm','waky',3),('risby','risby','Risby','6753331427','io.anotherdoor.wakyhabit','risby',2),('jangolog','jangolog','JangoLog','6769432656','io.anotherdoor.jangolog','jango',2)]
FOLDERS = {'en':'1.en','de':'2.de','es':'3.es','ja':'4.ja','zh-cn':'5.zh','fr':'7.fr','ko':'8.kr'}
def esc(v): return html.escape(str(v), quote=True)
def home(lang): return '/' if lang == 'en' else f'/{lang}/'
def url(lang, slug=None): return home(lang) + (f'apps/{slug}/' if slug else '')
def screenshot(p,lang,n=1):
    folder = '8.ko' if lang == 'ko' and p[1]=='jangolog' else FOLDERS[lang]
    return f'/images/{p[1]}/{folder}/{n}.png'
def stores(p):
    return f'<div class="stores"><a class="store" href="https://apps.apple.com/app/id{p[3]}" aria-label="{p[2]} — App Store"><span class="store-symbol" aria-hidden="true">↗</span> App Store</a><a class="store" href="https://play.google.com/store/apps/details?id={p[4]}" aria-label="{p[2]} — Google Play"><span class="store-symbol" aria-hidden="true">▷</span> Google Play</a></div>'
def icon(p): return f'<img class="app-icon" src="/images/{p[1]}/app_icon.png" alt="{p[2]}" width="64" height="64">'
def product(p,i,lang,t,detail=False):
    features=''.join(f'<li>{esc(x)}</li>' for x in t[33+i])
    return f'''<section class="product {p[5]}" id="{p[0]}"><div class="product-copy"><div class="product-name">{icon(p)}<span>{p[2]}</span></div><p class="eyebrow">0{i+1} / {esc(t[24+i])}</p><{'h1' if detail else 'h3'}>{esc(t[27+i])}</{'h1' if detail else 'h3'}><p class="description">{esc(t[30+i])}</p><ul class="features">{features}</ul>{stores(p)}{'' if detail else f'<a class="text-link" href="{url(lang,p[0])}">{esc(t[20])} <span aria-hidden="true">↗</span></a>'}</div><div class="product-visual"><span class="orbit" aria-hidden="true"></span><img src="{screenshot(p,lang)}" alt="{esc(p[2]+' — '+t[23])}" width="550" height="1120" {'fetchpriority="high"' if detail else 'loading="lazy"'}></div></section>'''
def render(lang,p=None):
    t=LOCALES[lang]; idx=PRODUCTS.index(p) if p else None
    title=f'{p[2]} — {t[27+idx]} | Another Door' if p else f'Another Door — {t[2]}'
    description=t[30+idx] if p else t[3]
    alternates=''.join(f'<link rel="alternate" hreflang="{l if l != "zh-cn" else "zh-Hans"}" href="{BASE}{url(l,p[0] if p else None)}">' for l in LOCALES)
    langs=''.join(f'<a href="{url(l,p[0] if p else None)}" lang="{l}" hreflang="{l}" {"aria-current=\"page\"" if l==lang else ""}>{esc(v[0])}</a>' for l,v in LOCALES.items())
    nav=f'''<header class="header"><a class="brand" href="{home(lang)}" aria-label="Another Door"><span class="door-mark" aria-hidden="true"></span>another door<span class="brand-dot">®</span></a><nav aria-label="{esc(t[5])}"><a href="{home(lang)}#apps">{esc(t[5])}</a><a href="{home(lang)}#about">{esc(t[6])}</a><a href="{home(lang)}#contact">{esc(t[7])}</a></nav><details class="language"><summary><span aria-hidden="true">◎</span> {t[0]} <span aria-hidden="true">⌄</span></summary><div class="language-menu">{langs}</div></details></header>'''
    if p:
        body=f'<div class="detail-top"><a class="text-link" href="{home(lang)}#apps">← {esc(t[21])}</a></div>'+product(p,idx,lang,t,True)+f'<section class="gallery"><p class="eyebrow">{esc(t[23])}</p><div class="gallery-grid">'+''.join(f'<img src="{screenshot(p,lang,n)}" alt="{esc(p[2])} — {esc(t[23])} {n}" loading="lazy" width="550" height="1120">' for n in range(1,p[6]+1))+f'</div>{stores(p)}</section>'
    else:
        minis=''.join(f'<a class="mini-app {x[5]}" href="#{x[0]}">{icon(x)}<span>{x[2]}<small>{esc(t[24+i])}</small></span><span aria-hidden="true">↗</span></a>' for i,x in enumerate(PRODUCTS))
        phones=''.join(f'<div class="hero-phone phone-{i}"><img src="{screenshot(x,lang)}" alt="{x[2]} — {esc(t[23])}" width="550" height="1120" {"fetchpriority=\"high\"" if i==1 else ""}></div>' for i,x in enumerate(PRODUCTS))
        body=f'''<section class="hero"><div class="hero-copy"><p class="eyebrow"><span class="live-dot"></span> ANOTHER DOOR / APP STUDIO</p><h1>{esc(t[1])}<br><span>{esc(t[2])}</span></h1><p class="hero-description">{esc(t[3])}</p><a class="button" href="#apps">{esc(t[4])} <span aria-hidden="true">↗</span></a></div><div class="hero-art"><div class="hero-disc" aria-hidden="true"></div>{phones}<span class="art-caption" aria-hidden="true">A LITTLE BETTER, EVERY DAY.</span></div></section><div class="mini-apps">{minis}</div><section class="section-intro" id="apps"><p class="eyebrow">{esc(t[5])}</p><h2>{esc(t[8])}</h2><p>{esc(t[9])}</p></section>'''+''.join(product(x,i,lang,t) for i,x in enumerate(PRODUCTS))+f'''<section class="about" id="about"><div><p class="eyebrow">{esc(t[6])}</p><h2>{esc(t[10])}</h2></div><div><p class="about-description">{esc(t[11])}</p><div class="principles">'''+''.join(f'<article><span class="principle-num">0{i+1}</span><h3>{esc(t[12+i*2])}</h3><p>{esc(t[13+i*2])}</p></article>' for i in range(3))+ '</div></div></section>'
    body+=f'''<section class="contact" id="contact"><p class="eyebrow">{esc(t[7])}</p><h2>{esc(t[18])}</h2><p>{esc(t[19])}</p><a href="mailto:support@anotherdoor.io">support@anotherdoor.io <span aria-hidden="true">↗</span></a></section>'''
    privacy = {'waky-alarm':'https://bane-u.github.io/waky/privacy.html','risby':'https://bane-u.github.io/waky-habit/privacy.html'}
    policy = f'<a href="{privacy[p[0]]}">{esc(t[22])}</a>' if p and p[0] in privacy else f'<a href="mailto:support@anotherdoor.io">{esc(t[7])}</a>'
    footer=f'<footer><a class="brand" href="{home(lang)}">another door<span class="brand-dot">®</span></a><span>© 2026 Another Door Inc.</span>{policy}</footer>'
    schema={'@context':'https://schema.org','@type':'SoftwareApplication' if p else 'Organization','name':p[2] if p else 'Another Door Inc.','url':BASE+url(lang,p[0] if p else None)}
    if p: schema.update(description=description,operatingSystem='iOS, Android',applicationCategory='LifestyleApplication' if idx<2 else 'FinanceApplication',image=BASE+'/images/'+p[1]+'/app_icon.png',installUrl=[f'https://apps.apple.com/app/id{p[3]}',f'https://play.google.com/store/apps/details?id={p[4]}'])
    else: schema.update(email='support@anotherdoor.io',description=t[11])
    return f'''<!doctype html><html lang="{'zh-Hans' if lang=='zh-cn' else lang}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{esc(title)}</title><meta name="description" content="{esc(description)}"><meta name="theme-color" content="#f7f7f2"><link rel="canonical" href="{BASE}{url(lang,p[0] if p else None)}">{alternates}<link rel="alternate" hreflang="x-default" href="{BASE}{url('en',p[0] if p else None)}"><meta property="og:type" content="website"><meta property="og:title" content="{esc(title)}"><meta property="og:description" content="{esc(description)}"><meta property="og:url" content="{BASE}{url(lang,p[0] if p else None)}"><meta property="og:image" content="{BASE}/images/social-card.png"><meta name="twitter:card" content="summary_large_image"><link rel="icon" href="/favicon.ico"><link rel="stylesheet" href="/styles.css"><script type="application/ld+json">{json.dumps(schema,ensure_ascii=False)}</script><script src="/script.js" defer></script></head><body>{nav}<main>{body}</main>{footer}</body></html>'''

def build():
    paths=[]
    for lang in LOCALES:
        for p in [None]+PRODUCTS:
            route=url(lang,p[0] if p else None)
            path=ROOT/route.lstrip('/')/'index.html'; path.parent.mkdir(parents=True,exist_ok=True); path.write_text(render(lang,p),encoding='utf-8'); paths.append(BASE+route)
    (ROOT/'sitemap.xml').write_text('<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'+''.join(f'<url><loc>{esc(x)}</loc></url>' for x in paths)+'</urlset>\n')
    (ROOT/'robots.txt').write_text(f'User-agent: *\nAllow: /\nSitemap: {BASE}/sitemap.xml\n')
    (ROOT/'.nojekyll').touch()
    print(f'Generated {len(paths)} pages.')
if __name__=='__main__': build()
